### ISSUE TITLE
Missing training scripts

### ISSUE THREAD

**Issue by bhanukaManesha** [erobic/ramen#2]
Is it possible to obtain the training scripts for `TDIUC`, `CLEVR-Humans` and `CLEVR-CoGenT`?

Also the following function cannot convert the `CLEVR-Humans` format. Was there another script that was used for this?
https://github.com/erobic/ramen/blob/81d1ba550cea9d7ac76823386cd47fde244bf091/preprocess/convert_from_clevr_to_vqa_format.py#L6

**Comment by erobic** [comment]
Hi,

I apologize for not porting the scripts for CLEVR-Humans/CoGenT and TDIUC into this new codebase. Unfortunately, I am not planning to include them anytime soon since it has been a very long time I last used some of those datasets. 

However, the following pointers might come in handy:

- CoGenT: This is probably the easiest to accommodate since everything should be identical to the CLEVR dataset.
- CLEVR-Humans: This would require support for new vocabulary (handled through: `preprocess_questions.sh`). Plus, as far as I remember it would also require additional output units for answer classes.
- TDIUC: Everything should be pretty similar to VQAv2 (except that the file format might need to be adjusted) + you would need features for the images which are not in Visual Genome.

The scripts may need adjustments based upon the input file formats.

Let me know if I can offer any other help.

**Comment by bhanukaManesha** [comment]
Hi,

Thank you very much for replying.

I will try to implement the scripts.

But, if by any chance you have the script to create the new vocabulary and convert the `CLEVR-Humans` dataset to VQA format, it would be very helpful. But it is understandable if you are unable to provide it.

**Comment by erobic** [comment]
Hi,

I added you to an older repository that has scripts related to what you are looking for e.g., `tools/process_text_CLEVR.sh` has stuff related to CLEVR-Humans. Please do note that this is an old repo and was not documented properly. Plus, I likely won't be adding scripts for the other datasets anytime soon. However, the old repo might have useful snippets for your own implementations.

**Comment by bhanukaManesha** [comment]
Hi,

I accepted the invitation. I will look into it. 

Thank You very much for the support. Appreciate it very much.
